# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ScreenRecoderForGame' do
pod 'JSPatch', '~> 1.0'
end

target 'ScreenRecoderForGameTests' do

end

target 'ScreenRecoderForGameUITests' do

end

